## Factor 6

In [1]:
import pandas as pd
import numpy as np

In [2]:
fielding_2023 = pd.read_csv("C:/Users/ASUS/OneDrive/Documents/實習/CPBL/原始資料/Fielding/2023.csv")

In [3]:
fielding_2023 = fielding_2023[fielding_2023['POS'] != 'P']

In [4]:
fielding_2023.rename(columns={'Name': '名稱'}, inplace=True)
fielding_2023.rename(columns={'Team Name': '球隊'}, inplace=True)

In [5]:
fielding_2023

       ID    名稱 Team ID  球隊 POS   G   TC   PO   A  E  DP  TP  PB  CS  SB
32   2285   高宇杰     ACN  中信   C  81  506  469  35  2   2   0   2  13  34
33   6430   福來喜     ACN  中信   C  53  313  287  23  3   3   0   2  10   9
34   6224  林吳晉瑋     ACN  中信   C  23   70   59  10  1   2   0   3   4   7
35    744   陳家駒     ACN  中信   C  14   51   50   1  0   0   0   0   1   7
36   3548   黃鈞聲     ACN  中信   C   5    8    8   0  0   0   0   0   0   0
..    ...   ...     ...  ..  ..  ..  ...  ...  .. ..  ..  ..  ..  ..  ..
414  1114   曾陶鎔     AAA  味全  RF   8   26   26   0  0   0   0   0   0   0
415  5341    邱辰     AAA  味全  RF   5    5    4   1  0   0   0   0   0   0
416  5296   董秉軒     AAA  味全  RF   3    1    1   0  0   0   0   0   0   0
417  5544   曾傳昇     AAA  味全  RF   1    1    0   0  1   0   0   0   0   0
418  6216   王順和     AAA  味全  RF   1    0    0   0  0   0   0   0   0   0

[272 rows x 15 columns]

In [6]:
def calculate_f6(row):
    if row['POS'] == 'P':
        return 0
    elif row['POS'] == 'C':
        return 1
    elif row['POS'] == '1B':
        return 2
    elif row['POS'] == '2B':
        return ((row['PO']+row['A'] / row['G']) / 4.8) * 6
    elif row['POS'] == '3B':
        return ((row['PO']+row['A'] / row['G']) / 2.65) * 4
    elif row['POS'] == 'SS':
        return ((row['PO']+row['A'] / row['G']) / 4.6) * 7
    elif row['POS'] in ['LF', 'CF', 'RF']:
        return ((row['PO']+row['A'] / row['G']) / 2.0) * 6
    else:
        return None

fielding_2023['F6'] = fielding_2023.apply(calculate_f6, axis=1)

In [7]:
fielding=fielding_2023.groupby(['名稱','球隊']).agg({'F6':'mean'})

In [8]:
fielding

               F6
名稱  球隊
于森旭 富邦  19.120192
何恆佑 統一   6.729859
余德龍 樂天  14.800725
全浩瑋 味全   1.000000
冉承霖 味全  25.800000
...           ...
高宇杰 中信   1.000000
黃勇傳 統一  30.910124
黃鈞聲 中信   1.000000
黃鈞麟 中信   0.000000
黃韋盛 中信   2.842531

[142 rows x 1 columns]

## Factor1~Factor5

In [9]:
excel_file_path = 'C:/Users/ASUS/OneDrive/Documents/實習/Rebas/CPBL_2023.xlsx'  # 請替換成你的 Excel 檔案路徑
sheet_name1 = 'AWAY-BOX-打擊'  # 請替換成你要載入的工作表名稱
sheet_name2 = 'HOME-BOX-打擊'

In [10]:
away = pd.read_excel(excel_file_path, sheet_name=sheet_name1)
home = pd.read_excel(excel_file_path, sheet_name=sheet_name2)

In [11]:
merged_stat = pd.concat([away, home], ignore_index=True)
merged_stat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6975 entries, 0 to 6974
Data columns (total 28 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   比賽編號    6975 non-null   int64
 1   比賽日期    6975 non-null   object
 2   球場      6975 non-null   object
 3   客場      6975 non-null   object
 4   主場      6975 non-null   object
 5   打序      6975 non-null   int64
 6   背號      6975 non-null   int64
 7   名稱      6975 non-null   object
 8   打席      6975 non-null   int64
 9   打數      6975 non-null   int64
 10  得分      6975 non-null   int64
 11  安打      6975 non-null   int64
 12  打點      6975 non-null   int64
 13  二安      6975 non-null   int64
 14  三安      6975 non-null   int64
 15  全壘打     6975 non-null   int64
 16  滾地雙殺    6975 non-null   int64
 17  雙殺      6975 non-null   int64
 18  三殺      6975 non-null   int64
 19  四壞      6975 non-null   int64
 20  故意四壞    6975 non-null   int64
 21  觸身      6975 non-null   int64
 22  三振      6975 non-null   int64
 23  犧短      6975 non-null   int64
 24  犧飛      6975 non-null   int64
 25  失誤上壘    6975 non-null   int64
 26  盜壘      6975 non-null   int64
 27  盜壘失敗    6975 non-null   int64
dtypes: int64(23), object(5)
memory usage: 1.5+ MB

In [12]:
merged_stat = merged_stat.drop(["球場","比賽編號","比賽日期","客場","主場","打序","背號",'雙殺','三殺','失誤上壘','打席','打點','犧短','犧飛','故意四壞'], axis = 1)
merged_stat

       名稱  打數  得分  安打  二安  三安  全壘打  滾地雙殺  四壞  觸身  三振  盜壘  盜壘失敗
0     董子恩   5   0   2   0   0    0     0   0   0   0   0     0
1     王念好   5   0   3   0   0    0     0   0   0   1   0     0
2     池恩齊   0   0   0   0   0    0     0   0   0   0   0     0
3      陳真   4   0   1   0   0    0     0   1   0   1   0     0
4     高國麟   1   0   0   0   0    0     0   1   0   0   0     0
...   ...  ..  ..  ..  ..  ..  ...   ...  ..  ..  ..  ..   ...
6970  張志豪   3   0   0   0   0    0     0   0   0   1   0     0
6971  曾頌恩   1   0   0   0   0    0     0   0   0   0   0     0
6972  福來喜   3   0   0   0   0    0     0   0   0   2   0     0
6973  高宇杰   1   0   0   0   0    0     0   0   0   0   0     0
6974  岳東華   3   1   1   0   0    0     1   1   0   1   0     0

[6975 rows x 13 columns]

In [13]:
agg_dict = {
    "打數": "sum",
    "得分": "sum",
    "安打": "sum",
    "二安": "sum",
    "三安": "sum",
    "全壘打": "sum",
    "滾地雙殺": "sum",
    "四壞": "sum",
    "觸身": "sum",
    "三振": "sum",
    "盜壘": "sum",
    "盜壘失敗": "sum"
}
batter_total = merged_stat.groupby("名稱").agg(agg_dict).reset_index()
batter_total

      名稱   打數  得分  安打  二安  三安  全壘打  滾地雙殺  四壞  觸身  三振  盜壘  盜壘失敗
0    于森旭   38   2   6   1   0    0     2   0   0   9   4     0
1    何恆佑   45   4   8   2   0    0     1   1   0  12   0     0
2    余德龍   48   5  10   1   0    1     1   1   0  12   0     1
3    全浩瑋    5   0   1   0   0    0     0   0   0   1   0     0
4    冉承霖   29   4   7   0   0    0     0   3   0  12   0     0
..   ...  ...  ..  ..  ..  ..  ...   ...  ..  ..  ..  ..   ...
145  高宇杰  212  14  40   4   0    1     4  14   0  54   1     0
146  黃勇傳  107  12  25   3   0    0     2  11   2  19   2     2
147  黃鈞聲   10   0   3   0   0    0     0   0   0   4   0     0
148  黃鈞麟    0   0   0   0   0    0     0   0   1   0   0     0
149  黃韋盛   80  14  18   2   0    0     3   6   0  25   0     0

[150 rows x 13 columns]

In [14]:
batter_total['一安']=batter_total['安打']-batter_total['二安']-batter_total['三安']-batter_total['全壘打']

In [15]:
batter_total['F1']=((batter_total['盜壘']+3)/(batter_total['盜壘']+batter_total['盜壘失敗']+7)-0.4)*20
batter_total['F2']=np.sqrt((batter_total['盜壘']+batter_total['盜壘失敗'])/(batter_total['一安']+batter_total['四壞']+batter_total['觸身']))/0.7
batter_total['F3']=batter_total['三安']/(batter_total['打數']-batter_total['全壘打']-batter_total['三振'])/0.0016
batter_total['F4']=25*(((batter_total['得分']-batter_total['全壘打'])/(batter_total['安打']+batter_total['四壞']+batter_total['觸身']-batter_total['全壘打']))-0.1)
batter_total['F5']=(0.063-(batter_total['滾地雙殺']/(batter_total['打數']-batter_total['全壘打']-batter_total['三振'])))/0.007

In [16]:
batter_total

,名稱,打數,得分,安打,二安,三安,全壘打,滾地雙殺,四壞,觸身,三振,盜壘,盜壘失敗,一安,F1,F2,F3,F4,F5
0,于森旭,38,2,6,1,0,0,2,0,0,9,4,0,5,4.727273,1.277753,0.0,5.833333,-0.852217
1,何恆佑,45,4,8,2,0,0,1,1,0,12,0,0,6,0.571429,0.000000,0.0,8.611111,4.670996
2,余德龍,48,5,10,1,0,1,1,1,0,12,0,1,8,-0.500000,0.476190,0.0,7.500000,4.918367
3,全浩瑋,5,0,1,0,0,0,0,0,0,1,0,0,1,0.571429,0.000000,0.0,-2.500000,9.000000
4,冉承霖,29,4,7,0,0,0,0,3,0,12,0,0,7,0.571429,0.000000,0.0,7.500000,9.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,高宇杰,212,14,40,4,0,1,4,14,0,54,1,0,35,2.000000,0.204082,0.0,3.632075,5.360328
146,黃勇傳,107,12,25,3,0,0,2,11,2,19,2,2,22,1.090909,0.482945,0.0,5.394737,5.753247
147,黃鈞聲,10,0,3,0,0,0,0,0,0,4,0,0,3,0.571429,0.000000,0.0,-2.500000,9.000000
148,黃鈞麟,0,0,0,0,0,0,0,0,1,0,0,0,0,0.571429,0.000000,NaN,-2.500000,NaN
149,黃韋盛,80,14,18,2,0,0,3,6,0,25,0,0,16,0.571429,0.000000,0.0,12.083333,1.207792

In [17]:
result= pd.merge(batter_total,fielding, on='名稱', how='outer')
result

,名稱,打數,得分,安打,二安,三安,全壘打,滾地雙殺,四壞,觸身,三振,盜壘,盜壘失敗,一安,F1,F2,F3,F4,F5,F6
0,于森旭,38,2,6,1,0,0,2,0,0,9,4,0,5,4.727273,1.277753,0.0,5.833333,-0.852217,19.120192
1,何恆佑,45,4,8,2,0,0,1,1,0,12,0,0,6,0.571429,0.000000,0.0,8.611111,4.670996,6.729859
2,余德龍,48,5,10,1,0,1,1,1,0,12,0,1,8,-0.500000,0.476190,0.0,7.500000,4.918367,14.800725
3,全浩瑋,5,0,1,0,0,0,0,0,0,1,0,0,1,0.571429,0.000000,0.0,-2.500000,9.000000,1.000000
4,冉承霖,29,4,7,0,0,0,0,3,0,12,0,0,7,0.571429,0.000000,0.0,7.500000,9.000000,25.800000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,高宇杰,212,14,40,4,0,1,4,14,0,54,1,0,35,2.000000,0.204082,0.0,3.632075,5.360328,1.000000
146,黃勇傳,107,12,25,3,0,0,2,11,2,19,2,2,22,1.090909,0.482945,0.0,5.394737,5.753247,30.910124
147,黃鈞聲,10,0,3,0,0,0,0,0,0,4,0,0,3,0.571429,0.000000,0.0,-2.500000,9.000000,1.000000
148,黃鈞麟,0,0,0,0,0,0,0,0,1,0,0,0,0,0.571429,0.000000,NaN,-2.500000,NaN,0.000000
149,黃韋盛,80,14,18,2,0,0,3,6,0,25,0,0,16,0.571429,0.000000,0.0,12.083333,1.207792,2.842531

In [18]:
result[['F1', 'F2', 'F3', 'F4', 'F5', 'F6']] = result[['F1', 'F2', 'F3', 'F4', 'F5', 'F6']].clip(lower=0, upper=10)
result[['F1', 'F2', 'F3', 'F4', 'F5', 'F6']] = result[['F1', 'F2', 'F3', 'F4', 'F5', 'F6']].fillna(0)

In [19]:
result

,名稱,打數,得分,安打,二安,三安,全壘打,滾地雙殺,四壞,觸身,三振,盜壘,盜壘失敗,一安,F1,F2,F3,F4,F5,F6
0,于森旭,38,2,6,1,0,0,2,0,0,9,4,0,5,4.727273,1.277753,0.0,5.833333,0.000000,10.000000
1,何恆佑,45,4,8,2,0,0,1,1,0,12,0,0,6,0.571429,0.000000,0.0,8.611111,4.670996,6.729859
2,余德龍,48,5,10,1,0,1,1,1,0,12,0,1,8,0.000000,0.476190,0.0,7.500000,4.918367,10.000000
3,全浩瑋,5,0,1,0,0,0,0,0,0,1,0,0,1,0.571429,0.000000,0.0,0.000000,9.000000,1.000000
4,冉承霖,29,4,7,0,0,0,0,3,0,12,0,0,7,0.571429,0.000000,0.0,7.500000,9.000000,10.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,高宇杰,212,14,40,4,0,1,4,14,0,54,1,0,35,2.000000,0.204082,0.0,3.632075,5.360328,1.000000
146,黃勇傳,107,12,25,3,0,0,2,11,2,19,2,2,22,1.090909,0.482945,0.0,5.394737,5.753247,10.000000
147,黃鈞聲,10,0,3,0,0,0,0,0,0,4,0,0,3,0.571429,0.000000,0.0,0.000000,9.000000,1.000000
148,黃鈞麟,0,0,0,0,0,0,0,0,1,0,0,0,0,0.571429,0.000000,0.0,0.000000,0.000000,0.000000
149,黃韋盛,80,14,18,2,0,0,3,6,0,25,0,0,16,0.571429,0.000000,0.0,10.000000,1.207792,2.842531

In [20]:
result['Speed Score']=(result['F1']+result['F2']+result['F3']+result['F4']+result['F5']+result['F6'])/6

In [21]:
result

,名稱,打數,得分,安打,二安,三安,全壘打,滾地雙殺,四壞,觸身,...,盜壘,盜壘失敗,一安,F1,F2,F3,F4,F5,F6,Speed Score
0,于森旭,38,2,6,1,0,0,2,0,0,...,4,0,5,4.727273,1.277753,0.0,5.833333,0.000000,10.000000,3.639727
1,何恆佑,45,4,8,2,0,0,1,1,0,...,0,0,6,0.571429,0.000000,0.0,8.611111,4.670996,6.729859,3.430566
2,余德龍,48,5,10,1,0,1,1,1,0,...,0,1,8,0.000000,0.476190,0.0,7.500000,4.918367,10.000000,3.815760
3,全浩瑋,5,0,1,0,0,0,0,0,0,...,0,0,1,0.571429,0.000000,0.0,0.000000,9.000000,1.000000,1.761905
4,冉承霖,29,4,7,0,0,0,0,3,0,...,0,0,7,0.571429,0.000000,0.0,7.500000,9.000000,10.000000,4.511905
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,高宇杰,212,14,40,4,0,1,4,14,0,...,1,0,35,2.000000,0.204082,0.0,3.632075,5.360328,1.000000,2.032747
146,黃勇傳,107,12,25,3,0,0,2,11,2,...,2,2,22,1.090909,0.482945,0.0,5.394737,5.753247,10.000000,3.786973
147,黃鈞聲,10,0,3,0,0,0,0,0,0,...,0,0,3,0.571429,0.000000,0.0,0.000000,9.000000,1.000000,1.761905
148,黃鈞麟,0,0,0,0,0,0,0,0,1,...,0,0,0,0.571429,0.000000,0.0,0.000000,0.000000,0.000000,0.095238
149,黃韋盛,80,14,18,2,0,0,3,6,0,...,0,0,16,0.571429,0.000000,0.0,10.000000,1.207792,2.842531,2.436959

In [22]:
#result.to_excel('Speed_Score.xlsx', index=True)